const productos = [
    { id: 1, nombre: "Sorrentinos", imagen:"images/sorreintinos.webp" , descripcion:"Pasta casera con salsa a elección, Pomarola, Carusso, Bolognesa",categoria:"pastas", precio: 500 },
    { id: 2, nombre: "Capelleties", imagen:"images/capelletis.webp", descripcion:"Pasta casera con salsa a elección, Pomarola, Carusso, Bolognesa",categoria:"pastas", precio: 300 },
    { id: 3, nombre: "Tallarines caseros",imagen:"images/tallarines.webp", descripcion:"Pasta casera con salsa a elección, Pomarola, Carusso, Bolognesa",categoria:"pastas", precio: 800 },
    { id: 4, nombre: "Ravioles",imagen:"images/ravioles.webp", descripcion:"Pasta casera con salsa a elección, Pomarola, Carusso, Bolognesa",categoria:"pastas", precio: 1000 },
    { id: 5, nombre: "Faina",imagen:"images/faina.webp",descripcion:"Las mejores minutas, prontas en minutos",categoria:"minuta", precio: 700 },
    { id: 6, nombre: "Chivito", imagen:"images/supr.webp",descripcion:"Las mejores minutas, prontas en minutos",categoria:"minuta", precio: 1200 },
    { id: 7, nombre: "Lomito", imagen:"images/finit.webp",descripcion:"Las mejores minutas, prontas en minutos",categoria:"minuta", precio: 600 },
    { id: 8, nombre: "Panchos", imagen:"images/panchos.webp",descripcion:"Las mejores minutas, prontas en minutos",categoria:"minuta", precio: 1100 },
    { id: 9, nombre: "Ensalada de Tomate", imagen:"images/ens.tomate.webp",descripcion:"Fresquitas hechas en el momento",categoria:"ensalada", precio: 900 },
    { id: 10, nombre: "Ensalada de lechuga", imagen:"images/ens_lechuga.webp",descripcion:"Fresquitas hechas en el momento",categoria:"ensalada", precio: 400 },
    { id: 11, nombre: "Ensalada Mixta",imagen:"images/ens.mixta.webp", descripcion:"Fresquitas hechas en el momento",categoria:"ensalada", precio: 1100 },
    { id: 12, nombre: "Ensalada el Nono",imagen:"images/ensalada_nono.webp", descripcion:"Fresquitas hechas en el momento",categoria:"ensalada", precio: 900 },
    { id: 13, nombre: "Flan con dulce",imagen:"images/flan.webp", descripcion:"Los mejores postres con opción Ligth",categoria:"postre", precio: 400 },
    { id: 14, nombre: "Chaja",imagen:"images/chaja.webp", descripcion:"Los mejores postres con opción Ligth",categoria:"postre", precio: 1100 },
    { id: 15, nombre: "Lemon Pie",imagen:"images/lemon_pie.webp",descripcion:"Los mejores postres con opción Ligth",categoria:"postre", precio: 900 },
    { id: 16, nombre: "Ensalada de Frutas",imagen:"images/ens.fruta.webp", descripcion:"Los mejores postres con opción Ligth",categoria:"postre", precio: 400 },
];
